/*
 * HeatPeak Studio TTRPG Platform - Legacy Backend Server
 * 
 * This is the main Express.js server for the original HeatPeak Studio TTRPG platform.
 * It represents the initial implementation of the system using Node.js, Express, and MongoDB.
 * This legacy codebase showcases the evolution from early prototype to modern architecture.
 * 
 * Key Technologies:
 * - Express.js for RESTful API server
 * - MongoDB with Mongoose ODM for data persistence
 * - CORS for cross-origin resource sharing
 * - Helmet for security middleware
 * - Static file serving for frontend assets
 * 
 * Architecture Pattern:
 * - Monolithic server serving both API and static frontend
 * - Document-based data modeling with MongoDB
 * - RESTful API design with centralized routing
 * 
 * Historical Context:
 * This represents the original "Ragnar" TTRPG concept under the HeatPeak Studio brand,
 * before the transition to Juggle Hive and modern .NET/Angular architecture.
 */

const express = require("express");
const mongoose = require("mongoose");
const app = express();
const path = require('path');
const cors = require('cors');
const helmet = require('helmet');
const apiRouter = require('./apiRouter.js');

// Load environment variables from .env file
const mongoURI = process.env.MONGODB_URI;

// Security and parsing middleware configuration
app.use(cors({
  origin: ["https://ragnar-legacy.onrender.com", "http://localhost"], // Allow specific origins
  credentials: true // Allow cookies and authentication headers
}));
app.use(express.json()); // Parse JSON request bodies

// Configure Helmet with custom CSP for React/Vite compatibility
app.use(helmet({
  contentSecurityPolicy: {
    directives: {
      defaultSrc: ["'self'"],
      scriptSrc: [
        "'self'",
        "'unsafe-inline'", // Required for Vite dev server and React
        "blob:", // Required for blob URLs generated by Vite
        "https://ragnar-legacy.onrender.com",
        "http://localhost:*", // Allow localhost with any port
        "https://localhost:*" // Allow HTTPS localhost with any port
      ],
      styleSrc: [
        "'self'",
        "'unsafe-inline'", // Required for React inline styles
        "https://fonts.googleapis.com"
      ],
      fontSrc: [
        "'self'",
        "https://fonts.gstatic.com"
      ],
      imgSrc: [
        "'self'",
        "data:", // Required for data URLs
        "blob:", // Required for blob URLs
        "https:"
      ],
      connectSrc: [
        "'self'",
        "https://ragnar-legacy.onrender.com",
        "http://localhost:*", // Allow localhost connections with any port
        "https://localhost:*", // Allow HTTPS localhost connections with any port
        "ws://localhost:*", // Allow WebSocket connections for Vite dev server
        "wss://localhost:*" // Allow secure WebSocket connections
      ],
      objectSrc: ["'none'"],
      upgradeInsecureRequests: []
    }
  }
}));

// API Routes - All API endpoints are handled through the centralized router
app.use('/api', apiRouter);

// Static File Serving - Serve the frontend built assets
app.use(express.static(path.join(__dirname, '../frontend/dist')));

// SPA Fallback - Handle client-side routing by serving index.html
// This ensures that frontend routes (like /character, /skills) work properly
app.get('/*', (req, res) => {
  if (!req.path.startsWith('/api')) {
    res.sendFile(path.join(__dirname, '../frontend/dist/index.html'));
  }
});

// connect MongoDB
mongoose.connect(mongoURI).then(() => {
    const PORT = 4000;
    app.listen(PORT, () => {
        console.log(`App is Listening on PORT ${PORT}`);
    })
}).catch(err => {
    console.log(err);
});
